# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_html": "00_scraping.ipynb",
         "cache": "00_scraping.ipynb",
         "CACHE_DIR": "00_scraping.ipynb",
         "find_links_by_func": "00_scraping.ipynb",
         "find_links_by_pattern": "00_scraping.ipynb",
         "run_in_parallel": "01_utility.ipynb",
         "FOOTBALL_DATA_LINK": "02_data.ipynb",
         "FOOTBALL_DATA_SEASONS": "02_data.ipynb",
         "League": "02_data.ipynb",
         "FOOTBALL_DATA_LEAGUES": "02_data.ipynb",
         "build_full_link": "02_data.ipynb",
         "BASE_URL": "03_sportde.ipynb",
         "season_links_from_page": "03_sportde.ipynb",
         "get_matchday_links": "03_sportde.ipynb",
         "get_matchday_dates": "03_sportde.ipynb",
         "get_match_infos": "03_sportde.ipynb",
         "get_standings": "03_sportde.ipynb",
         "scrape_season": "03_sportde.ipynb",
         "set_dtypes": "03_sportde.ipynb",
         "save_season": "03_sportde.ipynb",
         "read_football_csv": "04_feature_engineering.ipynb",
         "extract_teams": "04_feature_engineering.ipynb",
         "add_gamedays": "04_feature_engineering.ipynb",
         "add_points": "04_feature_engineering.ipynb",
         "add_positions": "04_feature_engineering.ipynb",
         "add_simple_diffs": "04_feature_engineering.ipynb",
         "results_from_goals": "04_feature_engineering.ipynb",
         "create_profit_df": "04_feature_engineering.ipynb",
         "add_profit_cols": "04_feature_engineering.ipynb"}

modules = ["scraping.py",
           "utility.py",
           "data/football_uk.py",
           "data/sportde.py",
           "feature_engineering.py"]

doc_url = "https://omlnaut.github.io/betting/"

git_url = "https://github.com/omlnaut/betting/tree/master/"

def custom_doc_links(name): return None
