# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_html": "00_scraping.ipynb",
         "find_links_by_func": "00_scraping.ipynb",
         "find_links_by_pattern": "00_scraping.ipynb"}

modules = ["scraping.py"]

doc_url = "https://omlnaut.github.io/betting/"

git_url = "https://github.com/omlnaut/betting/tree/master/"

def custom_doc_links(name): return None
