# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_utility.ipynb (unless otherwise specified).

__all__ = ['run_in_parallel']

# Cell
import multiprocessing as mp

# Cell
def run_in_parallel(func, iterable, n_workers=6):
    pool = mp.Pool(processes=n_workers)
    return pool.map(func, iterable)

# Cell
import pandas as pd