# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_data.ipynb (unless otherwise specified).

__all__ = ['FOOTBALL_DATA_LINK', 'FOOTBALL_DATA_SEASONS', 'League', 'FOOTBALL_DATA_LEAGUES', 'build_full_link']

# Cell
from dataclasses import dataclass
from pathlib import Path
import urllib.parse
from ..scraping import *

# Cell
FOOTBALL_DATA_LINK = r'https://www.football-data.co.uk/data.php'

# Cell
FOOTBALL_DATA_SEASONS = ['1314', '9900', '1112', '9697', '0708', '1920', '9798', '1819', '0405', '9596', '0001', '1213', '0203', '0102', '0809', '1617', '1516', '1718', '1011', '0506', '0607', '9899', '0304', '1415', '0910']

# Internal Cell
_FOOTBALL_DATA_LEAGUE_CODES = ['E0', 'E0', 'D1', 'I1', 'SP1', 'F1', 'N1', 'B1', 'P1', 'T1', 'G1']
_FOOTBALL_DATA_LEAGUE_NAMES = ['england', 'scotland', 'germany', 'italy', 'spain', 'france', 'netherlands', 'belgium', 'portugal', 'turkey', 'greece']

# Cell

@dataclass
class League:
    name: str
    code: str

# Cell
FOOTBALL_DATA_LEAGUES = [League(name=name, code=code) for name,code in zip(_FOOTBALL_DATA_LEAGUE_NAMES, _FOOTBALL_DATA_LEAGUE_CODES)]

# Cell
def build_full_link(season, league_code, mainpage_link):
    file_url = f'mmz4281/{season}/{league_code}.csv'
    return urllib.parse.urljoin(mainpage_link, file_url)